config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root "static_pages#index"
  resources :messages, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  has_many :recipients
  has_many :users, through: :recipients

  validates :sender_id, presence: true
  validates :body, presence: true

  def user_tokens=(ids)
    self.user_id = ids 
  end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
  belongs_to :message
  belongs_to :user

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, foreign_key: :sender_id
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = Recipient.where(user_id:  current_user.id).order("created_at DESC")
  end

  def new 
    @message = Message.new
    @recipients = Recipient.all
  end

  def create
    @message = current_user.messages.build message_params
    if @message.save 
      flash[:success] = "Message sent"
      redirect_to root_path
    else 
      flash[:alert] = "Great scott"
      render :new 
    end
  end

  private 
    def message_params
      params.require(:message).permit(:body :send_id, user_tokens: [])
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
      params.require(:user).permit :username, :email, :password, 
        :password_confirmation
    end

    def account_update_params
      params.require(:user).permit :username, :email, :password, 
        :password_confirmation, :current_password
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo">
      <%= link_to "Snap Message", root_path %>
    </div>
    <a href="javascrip:void(0)" class="navigation-menu-button" 
      id="js-mobile-menu"></a>
    <nav role="js-navigation-menu">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "New", new_message_path %></li>
          <li class="nav-link"><%= link_to "Inbox", message_path %></li>
          <li class="nav-link"><%= link_to "Log out", destroy_user_session_path %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign in", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnapMessage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div id="flash" class="flash<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
    
     <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Hello</h1>